-- 코드를 입력하세요

SELECT * FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID) >= 2) ORDER BY ID;


SELECT ID, NAME, h.HOST_ID FROM PLACES AS p
JOIN (
SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID) > 1
) AS h
ON p.HOST_ID = h.HOST_ID ORDER BY p.ID ASC;